JobConnect/Admin/Controllers/JobController.cs
using Admin.Helper;
using Entities;
using iTextSharp.text.pdf;
using Microsoft.AspNetCore.Mvc;
using OfficeOpenXml.FormulaParsing.Excel.Functions.Text;
using Services;
using ViewModel;
using ViewModel.Company;
using ViewModel.Job;
using ViewModel.User;
using ViewModel.UserJob;

namespace Admin.Controllers
{
    public class JobController : Controller
    {
        private readonly IJobService _jobService;
        private readonly ICommonService _commonService;
        private readonly ICompanyService _companyService;
        private readonly IStateService _stateService;
        private readonly IJobGroupsService _jobGroupsService;
        public JobController(IJobService jobService,
            ICommonService commonService,
            ICompanyService companyService,
            IStateService stateService,
            IJobGroupsService jobGroupsService)
        {
            _jobService = jobService;
            _commonService = commonService;
            _companyService = companyService;
            _stateService = stateService;
            _jobGroupsService = jobGroupsService;
        }

        public async Task<IActionResult> Index()
        {
            var response = await _companyService.GetJobs(new CompanyJobFilter
            {
                UserId = _commonService.GetCurrentUserId(),
                PageNumber = 1,
                PageSize = 7
            });
            var model = new CompanyJobFilter()
            {
                ContractTypes = _commonService.GetContractTypes(),
                Cities = await _stateService.GetGroupStates(),
                JobGroups = await _jobGroupsService.Get(),
                WorkExperienceYears = _commonService.GetWorkExperienceYears(),
                SalaryRequesteds = _commonService.GetSalaryRequesteds(),
                Latest = response,
                PageLengths = _commonService.GetPageLengths(),
                TotalRowNumber = response.FirstOrDefault()?.TotalRowCount,
                PageSize = 5
            };
            return View(model);
        }

        [HttpGet]
        public async Task<IActionResult> Get([FromQuery] CompanyJobFilter filter)
        {
            var response = await _companyService.GetJobs(filter);
            return PartialView("_Get", response);
        }

        [HttpGet]
        public async Task<IActionResult> Save(int id)
        {
            var currentUserId = _commonService.GetCurrentUserId();
            var model = new JobSave()
            {
                ContractTypes = _commonService.GetContractTypes(),
                Cities = await _stateService.GetGroupStates(),
                JobGroups = await _jobGroupsService.Get(),
                WorkExperienceYears = _commonService.GetWorkExperienceYears(),
                SalaryTypes = _commonService.GetSalaryRequesteds(),
                Genders = _commonService.GetGenders(),
                EducationLevels = _commonService.GetDegrees(),
                MilitaryStates = _commonService.GetMilitaryStatus(),
            };
            if (id == 0)
            {
                model.Status = true;
                return View(model);
            }
            var response = await _jobService.Detail(id);
            if (response != null)
            {
                model.Id = response.Id;
                model.CityId = response.CityId;
                model.ContractTypeId = response.ContractTypeId;
                model.EducationLevelRequired = response.EducationLevelRequiredId;
                model.GenderRequired = response.GenderRequiredId;
                model.JobGroupId = response.JobGroupId;
                model.MilitaryStateRequired = response.MilitaryStateRequiredId;
                model.WorkExperienceYearId = response.WorkExperienceYearId;
                model.Title = response.JobTitle;
                model.Description = response.Description;
                model.SalaryTypeId = response.SalaryTypeId;
                model.WorkingDays = response.WorkingDays;

                model.Status = response.Status;
                model.RequiredLoginToSite = response.RequiredLoginToSite;
                model.RequiredInformation = response.RequiredInformation;
                model.RequiredEducation = response.RequiredEducation;
                model.RequiredJob = response.RequiredJob;
                model.RequiredLanguage = response.RequiredLanguage;
                model.RequiredSkills = response.RequiredSkills;
                model.RequiredPriorities = response.RequiredPriorities;
            }

            return View(model);
        }

        [HttpPost]
        public async Task<IActionResult> Save([FromBody] JobSave request)
        {
            request.CompanyId = _commonService.GetCurrentCompanyId();
            if (!ModelState.IsValid)
            {
                return Ok(new ResponseBase(false, HelperExtension.Errors(ModelState)));
            }
            request.UserId = _commonService.GetCurrentUserId();
            var response = await _jobService.Save(request);
            return Ok(response);
        }
    }
}

JobConnect/Admin/Views/Job/Index.cshtml
@model ViewModel.Company.CompanyJobFilter
@{
    ViewBag.Title = " آگهی های شغلی";
}
<section class="ftco-section col-md-12">
    <div class="panel panel-default">
        <div class="panel-heading wt-panel-heading p-a10">
            <h4 class="panel-tittle m-a0">
                <i class="fa fa-list"></i>
                @ViewBag.Title
            </h4>
        </div>
        <div class="panel-body wt-panel-body p-a10 m-b30 ">
            <div class="row col-md-12">
                <div class="col-md-3">
                    <form id="job-form">
                        <div class="form-group row col-md-12">
                            <div class="col-md-12">
                                <input class="form-control" asp-for="JobTitle" placeholder="عنوان آگهی" />
                            </div>
                        </div>
                        <div class="form-group row col-md-12">
                            <div class="col-md-12">
                                <app-select asp-for="JobGroupId" asp-items="@Model.JobGroups"></app-select>
                            </div>
                        </div>
                        <div class="form-group row col-md-12">
                            <div class="col-md-12">
                                <app-select asp-for="CityId" asp-items="@Model.Cities"></app-select>
                            </div>
                        </div>
                        <div class="form-group row col-md-12">
                            <div class="col-md-12">
                                <app-select asp-for="ContractTypeId" asp-items="@Model.ContractTypes"></app-select>
                            </div>
                        </div>
                        <div class="form-group row col-md-12">
                            <div class="col-md-12">
                                <app-select asp-for="SalaryRequestedId" asp-items="@Model.SalaryRequesteds"></app-select>
                            </div>
                        </div>

                        <div class="form-group row col-md-12">
                            <div class="col-md-12">
                                <app-select asp-for="WorkExperienceYearId" asp-items="@Model.WorkExperienceYears"></app-select>
                            </div>
                        </div>
                        <div class="form-group row col-md-12">
                            <div class="col-md-12">
                                <app-select asp-for="PageSize" key="@Model.PageSize" asp-items="@Model.PageLengths"></app-select>
                            </div>
                        </div>

                        <div class="form-group row col-md-12 text-center">
                            <a id="search-form" class="btn btn-success ">
                                <i class="fa fa-search"></i>
                                جستجو
                            </a>
                        </div>
                    </form>
                </div>
                <div class="col-md-9">
                    <a href="/job/save" class="btn btn-primary mb-2">
                        <i class="fa fa-plus"></i>
                        ایجاد آگهی
                    </a>

                    <div class="row">
                        <div class="twm-pro-view-chart-wrap col-md-12">
                            <div class="panel panel-default">
                                <div class="panel-heading wt-panel-heading p-a10">
                                    <h4 class="panel-tittle m-a0">
                                        <i class="fa fa-list"></i>
                                        @ViewBag.Title
                                        @*<span>@Model.TotalRowNumber</span>*@
                                    </h4>
                                </div>
                                <div class="panel-body wt-panel-body p-a5 m-b10 table-response" id="response">
                                    @if (Model.Latest != null)
                                    {
                                        <partial name="~/Views/Job/_Get.cshtml" model="@Model.Latest" />
                                    }
                                </div>
                            </div>
                        </div>

                    </div>

                </div>
            </div>
        </div>
    </div>
</section>


<script type="systemjs-module" src="/dist/company-job.js"></script>

JobConnect/Admin/Views/Job/Save.cshtml
@model ViewModel.Job.JobSave
@{
    ViewBag.Title = " ثبت آگهی";
}
<style>
    .dropdown-menu > li > a {
        display: block;
        padding: 3px 20px;
        clear: both;
        font-weight: normal;
        line-height: 1.42857143;
        color: #333;
        white-space: nowrap;
    }
    div{
        line-height:1.6;
    }
</style>
<div class="panel panel-default">
    <div class="panel-heading wt-panel-heading p-a20">
        <h4 class="panel-tittle m-a0">
            <i class="fa fa-list"></i>
            @ViewBag.Title
        </h4>
    </div>
    <div class="panel-body wt-panel-body p-a20 m-b30 ">
        <div class="alert alert-info">
            <div>
                <i class="fa fa-info"></i>
                با انتخاب فیلد مشخصات تکمیلی متقاضی مورد نظر باید نام،نام خانوادگی،شماره تماس،تاریخ تولد را باید وارد نماید
            </div>

            <div>
                <i class="fa fa-info"></i>
                با انتخاب هر کدام از فیلدهای
                <span class="gray-color ">
                    <i class="fa fa-graduation-cap"></i>
                    سوابق تحصیلی/آموزشی
                </span>
                <span class="gray-color ">
                    <i class="fa fa-tasks"></i>
                    سوابق شغلی
                </span>
                <span class="gray-color ">
                    <i class="fa fa-language"></i>
                    اطلاعات زبان ها
                </span>
                <span class="gray-color ">
                    <i class="fa fa-map"></i>
                    مهارت های شغلی
                </span>
                متقاضی مورد نظر حداقل باید یک مورد وارد نماید
            </div>
        </div>
        <form id="job-save-form">
            <input type="hidden" asp-for="Id" />
            <div class="row col-md-12">
                <div class="col-md-6">
                    <div class="form-group row col-md-12">
                        <label class="label-control col-md-4" asp-for="Title"></label>
                        <div class="col-md-8">
                            <input class="form-control" asp-for="Title">
                        </div>
                    </div>

                    <div class="form-group row col-md-12">
                        <label class="label-control col-md-4" asp-for="JobGroupId"></label>
                        <div class="col-md-8">
                            <app-select asp-for="JobGroupId" key="@Model.JobGroupId" asp-items="@Model.JobGroups"></app-select>
                        </div>
                    </div>

                    <div class="form-group row col-md-12">
                        <label class="label-control col-md-4" asp-for="CityId"></label>
                        <div class="col-md-8">
                            <app-select asp-for="CityId" key="@Model.CityId" asp-items="@Model.Cities"></app-select>
                        </div>
                    </div>

                    <div class="form-group row col-md-12">
                        <label class="label-control col-md-4" asp-for="WorkExperienceYearId"></label>
                        <div class="col-md-8">
                            <app-select asp-for="WorkExperienceYearId" key="@Model.WorkExperienceYearId" asp-items="@Model.WorkExperienceYears"></app-select>
                        </div>
                    </div>
                    <div class="form-group row col-md-12">
                        <label class="label-control col-md-4" asp-for="ContractTypeId"></label>
                        <div class="col-md-8">
                            <app-select asp-for="ContractTypeId" key="@Model.ContractTypeId" asp-items="@Model.ContractTypes"></app-select>
                        </div>
                    </div>

                    <div class="form-group row col-md-12">
                        <label class="label-control col-md-4" asp-for="WorkingDays"></label>
                        <div class="col-md-8">
                            <textarea class="form-control" asp-for="WorkingDays">
                                @Model.WorkingDays
                            </textarea>
                        </div>
                    </div>
                </div>
                <div class="col-md-6">
                    <div class="form-group row col-md-12">
                        <label class="label-control col-md-4" asp-for="SalaryTypeId"></label>
                        <div class="col-md-8">
                            <app-select asp-for="SalaryTypeId" key="@Model.SalaryTypeId" asp-items="@Model.SalaryTypes"></app-select>
                        </div>
                    </div>
                    <div class="form-group row col-md-12">
                        <label class="label-control col-md-4" asp-for="GenderRequired"></label>
                        <div class="col-md-8">
                            <app-select asp-for="GenderRequired" key="@Model.GenderRequired" asp-items="@Model.Genders"></app-select>
                        </div>
                    </div>
                    <div class="form-group row col-md-12">
                        <label class="label-control col-md-4" asp-for="EducationLevelRequired"></label>
                        <div class="col-md-8">
                            <app-select asp-for="EducationLevelRequired" key="@Model.EducationLevelRequired" asp-items="@Model.EducationLevels"></app-select>
                        </div>
                    </div>
                    <div class="form-group row col-md-12">
                        <label class="label-control col-md-4" asp-for="MilitaryStateRequired"></label>
                        <div class="col-md-8">
                            <app-select asp-for="MilitaryStateRequired" key="@Model.MilitaryStateRequired" asp-items="@Model.MilitaryStates"></app-select>
                        </div>
                    </div>
                    <div class="form-group row col-md-12">
                        <div class="col-md-12">
                            <div class="row col-md-12">
                                <div class="col-md-6 p-0">
                                    <div>
                                        <input class="label-control " type="checkbox" asp-for="Status">
                                        <label asp-for="Status"></label>
                                    </div>
                                    <div>
                                        <input type="checkbox" asp-for="RequiredLoginToSite">
                                        <label class="label-control " asp-for="RequiredLoginToSite"></label>
                                    </div>
                                    <div>
                                        <input type="checkbox" class="RequiredLoginToSite" asp-for="RequiredInformation">
                                        <label class="label-control " asp-for="RequiredInformation"></label>
                                    </div>
                                    <div>
                                        <input type="checkbox" class="RequiredLoginToSite" asp-for="RequiredEducation">
                                        <label class="label-control " asp-for="RequiredEducation"></label>
                                    </div>
                                </div>
                                <div class="col-md-6 p-0">
                                    <div>
                                        <input type="checkbox" class="RequiredLoginToSite" asp-for="RequiredJob">
                                        <label class="label-control " asp-for="RequiredJob"></label>
                                    </div>
                                    <div>
                                        <input type="checkbox" class="RequiredLoginToSite" asp-for="RequiredLanguage">
                                        <label class="label-control " asp-for="RequiredLanguage"></label>
                                    </div>
                                    <div>
                                        <input type="checkbox" class="RequiredLoginToSite" asp-for="RequiredSkills">
                                        <label class="label-control " asp-for="RequiredSkills"></label>
                                    </div>
                                    @*<div>
                                            <input type="checkbox" asp-for="RequiredPriorities">
                                            <label class="label-control " asp-for="RequiredPriorities"></label>
                                        </div>*@
                                </div>
                            </div>
                        </div>
                    </div>
                </div>
                <div class="col-md-12">
                    <div>
                        <label class="label-control" asp-for="Description"></label>
                    </div>
                    <div class="form-group row col-md-12">
                        <div class="col-md-12">
                            <textarea class="form-control" asp-for="Description">
                             </textarea>
                        </div>
                    </div>
                </div>
            </div>

        </form>
    </div>
    <div class="panel-footer text-center">
        <a id="submit" class="btn btn-success mb-2 ">
            <i class="fa fa-sign-in-alt"></i>
            ثبت
        </a>
    </div>
</div>



<script type="systemjs-module" src="/dist/job-save.js"></script>

JobConnect/Admin/Views/Job/_Get.cshtml
@model List<ViewModel.Company.CompanyJobResponse>
@using DNTPersianUtils.Core
@{
    var pageNumber = @Model.FirstOrDefault()?.PageNumber.GetValueOrDefault();
    var pageSize = @Model.FirstOrDefault()?.PageSize ?? 0;
    var totalRowNumber = @Model.FirstOrDefault()?.TotalRowCount ?? 0;
}

<table class="table table-striped">
    <thead class="text-center">
        <tr>
            <th scope="col">#</th>
            <th scope="col">عنوان</th>
            <th scope="col">تاریخ</th>
            <th scope="col">شهر</th>
            <th scope="col">وضعیت</th>
            <th scope="col">تعداد رزومه دریافتی</th>
            <th scope="col">عملیات</th>

        </tr>
    </thead>
    <tbody>

        @foreach (var item in Model)
        {
            <tr class="align-baseline">
                <th scope="row">@((pageNumber * pageSize) + Model.IndexOf(item) + 1)</th>
                <td>@item.JobTitle</td>
                <td>@item.DateTime.ToPersianDateTextify()</td>
                <td>@item.Status</td>
                <td>
                    @if (item.Status)
                    {
                        <i class="fa fa-check"></i>
                    }
                    else
                    {
                        <i class="fa fa-times"></i>
                    }
                </td>
                <td>@item.JobRequestedCount</td>
                <td>
                    <a href="/job/save/@item.JobId" class="btn twm-jobs-browse site-text-primary ">
                        <i class="fa fa-edit"></i>
                    </a>
                    <a href="/JobRequest/Detail/@item.JobId" class="btn twm-jobs-browse site-text-primary">
                        <i class="fa fa-list"></i>
                    </a>
                </td>




            </tr>
        }
    </tbody>
</table>

@*<div class=" col-md-6 twm-jobs-list-style1 mb-1" style="padding:10px;width:49%;float:right">
    <div class="row col-md-12">
        <ul>
            <li>
                <span class="twm-job-address">
                    <span class="gray-color"> ردیف:</span>
                    @((pageNumber * pageSize) + Model.IndexOf(item) + 1)
                </span>
            </li>
            <li>
                <span class="twm-job-address">
                    <span class="gray-color"> عنوان شغلی:</span>
                    @if (item.JobTitle.Length > 30)
                    {
                        <span title="@item.JobTitle">
                            @item.JobTitle.Substring(0, 27)
                            <span>...</span>
                        </span>
                    }
                    else
                    {
                        <span>@item.JobTitle</span>
                    }
                </span>
            </li>
            <li>
                <span class="twm-job-address">
                    <span class="gray-color">تاریخ:</span>
                    <span>
                        @item.DateTimeString
                        <span class="gray-color">
                            (@item.DateTime.ToShortPersianDateString())
                        </span>
                    </span>
                </span>
            </li>
            <li>
                <span class="twm-job-address">
                    <span class="gray-color">وضعیت:</span>
                    @if (item.Status)
                    {
                        <i class="fa fa-check"></i>
                    }
                    else
                    {
                        <i class="fa fa-times"></i>
                    }
                </span>
            </li>
            <li>
                <span class="twm-job-address">
                    <span class="gray-color">رزمه های دریافت شده:</span>
                    @item.JobRequestedCount
                </span>
            </li>

            <li>
                <span class="twm-job-address">
                    <span class="gray-color">شهر:</span>
                    @item.CityName
                </span>
            </li>

            <li>
                <span class="twm-job-address">
                    <span class="gray-color">گروه شغلی :</span>
                    @item.JobGroupName
                </span>
            </li>
            <li>
                <span class="twm-job-address">
                    <span class="gray-color">نوع قرارداد :</span>
                    @item.ContractTypeName
                </span>
            </li>

            <li>
                <span class="twm-job-address">
                    <span class="gray-color">سابقه کاری :</span>
                    @item.WorkExperienceYearName
                </span>
            </li>
            <li>
                <span class="twm-job-address">
                    <span class="gray-color">حقوق درخواست :</span>
                    @item.SalaryRequestedName
                </span>
            </li>
            <li>
                <hr />
            </li>
            <li>
                <a href="/job/save/@item.JobId" class="btn twm-jobs-browse site-text-primary ">
                    <i class="fa fa-edit"></i>
                    ویرایش آگهی
                </a>
                <a href="/JobRequest/Detail/@item.JobId" class="btn twm-jobs-browse site-text-primary">
                    <i class="fa fa-search"></i>
                    رزومه های ارسال شده
                </a>
            </li>
        </ul>
    </div>
</div>*@


@if (Model.FirstOrDefault()?.TotalRowCount > 0)
{
    <div class="row col-md-12 pagination-outer">
        <div class="pagination-style1">
            <app-pager asp-controller="Job"
                       asp-action="Get"
                       first-text="ابتدا"
                       last-text="انتها"
                       show-first-last="true"
                       page-number="@pageNumber.GetValueOrDefault() + 1"
                       page-size="@pageSize"
                       is-ajax="true"
                       ajax-container="#"
                       total-page-number="@totalRowNumber"></app-pager>
        </div>
    </div>
}